# Generated by Django 5.1.1 on 2024-10-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postmodel_available_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
