# Generated by Django 5.0.6 on 2025-03-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_no', models.DateField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
