# Generated by Django 5.0.6 on 2025-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_no',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
