# Generated by Django 5.1.1 on 2024-10-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterings', '0002_district_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
    ]
