# Generated by Django 5.1.1 on 2024-09-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemodel',
            name='note',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='favoritemodel',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
