# Generated by Django 5.1.1 on 2024-10-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritemodel',
            old_name='note',
            new_name='post_title',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='post_detail_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='post_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
